### PR TITLE
build : add main branch #7

### LINKED ISSUE #7: Create main branch

### PR DESCRIPTION
**Pull request by busesisi**
Created main branch

### CODE REVIEW

**Comment by ceyhungulbas** [comment]
I think this should work! At least I hope...

**Review by ceyhungulbas — APPROVED** [review]
I think this should work! At least I hope...
Also this is first PR in our capstone project, so hoorrraayy! 🎉 🎉

**Review by ceyhungulbas — CHANGES_REQUESTED** [review]
Btw Buse, I just remembered about naming commit thanks to Deniz.
Can you change commit name to "Build : add main branch"

resim
resim

**Review by ceyhungulbas — APPROVED** [review]
Ellerine saglik! :')

**Comment by halitbatur** [comment]
@busesisi main branch is already pushed this PR is not needed since we dont want to apply any changes to dev branch, u just created main and pushed it to the repo, so i will be closing this PR

**Pull request closed without merging**
