### PR TITLE
Build : add packages & file structure

### LINKED ISSUE #5: Download necessary packages

### PR DESCRIPTION
**Pull request by udenizdemirbilek**
Close #5  add Firebase, CircleCI, Netlify, Bootstrap, Sass, i18n.js to packages with yarn, modify .gitignore to ignore .yarn, add component and container folders

### CODE REVIEW

**Review by busesisi — APPROVED** [review]
I think we have all the packages we need. Thank you Deniz.

**Comment by halitbatur** [comment]
@udenizdemirbilek What is the .pnp.cjs file used for ?

**Comment by udenizdemirbilek** [comment]
> 
> 
> @udenizdemirbilek What is the .pnp.cjs file used for ?

@halitbatur I don't know but it seems there's a huge list of dependencies inside it, so maybe yarn created it? I didn't create it manually.
Do you want me to include it in .gitignore?

**Comment by halitbatur** [comment]
@udenizdemirbilek usually yarn creates the yarn.lock which is normal but I never seen this .pnp file lemme check it out first

**Comment by udenizdemirbilek** [comment]
Deleting branch

**Pull request closed without merging**
