### PR TITLE
Build: add firebase config

### LINKED ISSUE #6: Configure firebase

### PR DESCRIPTION
**Pull request by ceyhungulbas**
closed #6

### CODE REVIEW

**Review by udenizdemirbilek — CHANGES_REQUESTED** [review]
Good job! 👍 However there's one minor issue,

Could you change the heading to "Build : add firebase config" ?
Past tense and capitalized first letters are not used according to project manual.

Please check your commit message as well
image
image

**Comment by ceyhungulbas** [comment]
You're totally right! It escaped me 😅

**Review by udenizdemirbilek — APPROVED** [review]
Good job! LGTM 👍

**Comment by halitbatur** [comment]
@ceyhungulbas looks good to me

**Review by halitbatur — APPROVED** [review]

**Comment by halitbatur** [comment]
@ceyhungulbas I think u will need to run ```yarn run fix``` cause the deploy tests are failing

**Comment by ceyhungulbas** [comment]
@halitbatur The problem was removing react default codes. I removed because we are not going to need it but I added back. So its working now. Thank you!

**Pull request merged**
